version: '3'
services:
  laminas-app:
    image: shinsenter/laminas:latest
    volumes:
      - ./my-website:/var/www/html
      - ./ssl-certs:/etc/ssl/web
    environment:
      TZ: UTC
      PUID: ${UID:-9999}
      PGID: ${GID:-9999}
    ports:
      - "80:80"
      - "443:443"
    links:
      - db
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
  ## OTHER CONTAINERS SUCH AS REDIS OR DATABASE ###################################
  db:
    image: mysql:latest
    environment:
      TZ: UTC
      MYSQL_ROOT_PASSWORD: mydb_p@ssw0rd
      MYSQL_DATABASE: gallery_database
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      
volumes:
  dbdata: